## IMPORTS


In [11]:
#pip install pandas
#pip install numpy
#pip install -U scikit-learn

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

# Counter proporciona un diccionario donde cada elemento distinto se almacena 
# como claves con un valor asociado igual a su cuenta
from collections import Counter
 


import sklearn
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.neighbors import KNeighborsClassifier

from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.model_selection import cross_val_score, StratifiedKFold
 
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer 
from sklearn.model_selection import cross_val_predict
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
 
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.dummy import DummyClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

 
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import classification_report
from sklearn.metrics import roc_curve, roc_auc_score

# DOCUMENTACIÓN
https://scikit-learn.org/stable/api/index.html

## Creación de un modelo con Sklearn

En la celda a continuación se resumen las características mas importantes si creamos un modelo a 'mano' con sklearn.
ESTO ESTÁ INCLUIDO DENTRO DEL METODO UTILITARIO DE entrenar_y_obtener_accuracy. No usar a menos que manden cambiar parámetros.


In [12]:
from sklearn.neighbors import KNeighborsClassifier

# We instantiate a new KNeighborsClassifier object that will represent our model
modelo = KNeighborsClassifier(n_neighbors=3)
# then , we adjust the model to the training data 
#modelo.fit(X, y)

#Now , we can say our model has been trained. It's time for testing.
# We do that by making our model classify unknown data 
#modelo.predict(X_test)

#in case we would like to see the probabilty each element has to belong to one class or another..
#modelo.predict_proba(X_test)


#results are given inside an array of vectors.

#IN ORDER TO SEE WHICH PARAMETERS ARE BEING USED TO TRAIN THE MODEL: 
#modelo.get_params()
"""
{'algorithm': 'auto',
 'leaf_size': 30,
 'metric': 'minkowski',
  'metric_params': None,
 'n_jobs': None,
 'n_neighbors': 3,
 'p': 2, 
 'weights': 'uniform'}
"""


"\n{'algorithm': 'auto',\n 'leaf_size': 30,\n 'metric': 'minkowski',\n  'metric_params': None,\n 'n_jobs': None,\n 'n_neighbors': 3,\n 'p': 2, \n 'weights': 'uniform'}\n"

## Métodos utilidad - métricas del clasificador

In [13]:
def entrenar_y_obtener_accuracy(X_train, y_train, X_test, y_test, k=3):
    modelo = KNeighborsClassifier(n_neighbors=k)
    modelo.fit(X_train, y_train)
    y_pred = modelo.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    conf_matrix = confusion_matrix(y_test, y_pred)
    print(f'La accuracy es: {accuracy:.2f}')
    print('Matriz de confusión:\n', conf_matrix)
    return modelo, y_pred

## Pipelines


In [14]:
#from sklearn.pipeline import Pipeline
'''
df = pd.read_csv('NOMBREFICHERO')
print(df.info())

# Dividir el conjunto de datos en variables (X) y etiquetas (y)
X = df.drop(columns=['clase_objetivo'])
y = df['clase_objetivo']

# Dividir en conjuntos de entrenamiento y test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


# Definir los trnsformers necesarios
numeric_features = ['variable1', 'variable2']
categorical_features = ['variable_categorica']

# Crear el pipeline de preprocesamiento

# Para ello creamos un transformer para variables numéricas y otro para variables categóricas
numeric_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='mean')), 
    ('scaler', StandardScaler()) 
])

categorical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('encoder', OneHotEncoder(handle_unknown='ignore'))
])

#y se lo pasamos a la pipeline de preprocesamiento de datos
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numeric_features),
        ('cat', categorical_transformer, categorical_features)
    ])


## USO DEL PIPELINE.

# Incluir el clasificador en el pipeline
modelo = KNeighborsClassifier(n_neighbors=3)

# Crear el pipeline final  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', modelo)
])

'''

"\ndf = pd.read_csv('NOMBREFICHERO')\nprint(df.info())\n\n# Dividir el conjunto de datos en variables (X) y etiquetas (y)\nX = df.drop(columns=['clase_objetivo'])\ny = df['clase_objetivo']\n\n# Dividir en conjuntos de entrenamiento y test\nX_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)\n\n\n# Definir los trnsformers necesarios\nnumeric_features = ['variable1', 'variable2']\ncategorical_features = ['variable_categorica']\n\n# Crear el pipeline de preprocesamiento\n\n# Para ello creamos un transformer para variables numéricas y otro para variables categóricas\nnumeric_transformer = Pipeline(steps=[\n    ('imputer', SimpleImputer(strategy='mean')), \n    ('scaler', StandardScaler()) \n])\n\ncategorical_transformer = Pipeline(steps=[\n    ('imputer', SimpleImputer(strategy='most_frequent')),\n    ('encoder', OneHotEncoder(handle_unknown='ignore'))\n])\n\n#y se lo pasamos a la pipeline de preprocesamiento de datos\npreprocessor = ColumnTransformer(

## Cargar un conjunto de datos e inizializar las variables correctamente


### Entrenamiento y validación en ficheros distintos

In [15]:
# Datos de entrenamiento-EN CASO DE QUE NOS DEN LOS GRUPOS SEPARADOS
'''
df_train = pd.read_csv('NOMBREFICHERO.csv')  
print(df_train.describe())
print(df_train.shape)
# Datos de evaluación - EN CASO DE QUE NOS DEN LOS GRUPOS SEPARADOS
df_test = pd.read_csv('NOMBREFICHERO.csv')
X_test = df_test.drop('Clase', axis = 1)
y_test = df_test[['Clase']].to_numpy().ravel()
'''

"\ndf_train = pd.read_csv('NOMBREFICHERO.csv')  \nprint(df_train.describe())\nprint(df_train.shape)\n# Datos de evaluación - EN CASO DE QUE NOS DEN LOS GRUPOS SEPARADOS\ndf_test = pd.read_csv('NOMBREFICHERO.csv')\nX_test = df_test.drop('Clase', axis = 1)\ny_test = df_test[['Clase']].to_numpy().ravel()\n"

 Lo habitual es tener que usar esquemas de validación a la hora de separar los datos. Por lo que nos darán un dataset "entero"


### Esquemas de validación


####  Holdout validation - DIVISION ENTRENAMIENTO TEST

usar este código si nos piden holdout!!! Es importante ya que no se separan primero los conjuntos y luego usamos SOLO el de entrenamiento para el preprocesado, de tal forma que el grupo de validación sea completamente ajeno al proceso de entrenamiento

El primero de la práctica usa el conjunto entero para preprocesado 

In [16]:
'''
df = pd.read_csv('NOMBREFICHERO.csv')
print(df.info())
print(df.describe())

X = df.drop('Clase', axis = 1)
y = df['Clase']

print("Resultados con semilla 0:")
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=0, stratify = y)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
entrenar_y_obtener_accuracy(X_train, y_train, X_test, y_test)

print("Resultados con semilla 1003:")
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=1003, stratify = y)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
entrenar_y_obtener_accuracy(X_train, y_train, X_test, y_test)

print("Resultados con semilla 19:")
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=19, stratify = y)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
entrenar_y_obtener_accuracy(X_train, y_train, X_test, y_test)
'''

'\ndf = pd.read_csv(\'NOMBREFICHERO.csv\')\nprint(df.info())\nprint(df.describe())\n\nX = df.drop(\'Clase\', axis = 1)\ny = df[\'Clase\']\n\nprint("Resultados con semilla 0:")\nX_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=0, stratify = y)\nscaler = StandardScaler()\nX_train = scaler.fit_transform(X_train)\nX_test = scaler.transform(X_test)\nentrenar_y_obtener_accuracy(X_train, y_train, X_test, y_test)\n\nprint("Resultados con semilla 1003:")\nX_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=1003, stratify = y)\nscaler = StandardScaler()\nX_train = scaler.fit_transform(X_train)\nX_test = scaler.transform(X_test)\nentrenar_y_obtener_accuracy(X_train, y_train, X_test, y_test)\n\nprint("Resultados con semilla 19:")\nX_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=19, stratify = y)\nscaler = StandardScaler()\nX_train = scaler.fit_transform(X_train)\nX_test

##### usando un pipeline 
(HABRÍA QUE CREAR EL PIPELINE CORRESPONDIENTE PRIMERO...  ES POR MOSTRAR QUE SE PASA EL PIPELINE DE FORMA INDEPENDIENTE AL CONJUNTO DE ENTRENAMIENTO,)


In [17]:
'''
# Entrenar el modelo en el conjunto de datos de entrenamiento
pipeline.fit(X_train, y_train)

# Evaluar el modelo en el conjunto de datos de test
y_pred = pipeline.predict(X_test)

'''

'\n# Entrenar el modelo en el conjunto de datos de entrenamiento\npipeline.fit(X_train, y_train)\n\n# Evaluar el modelo en el conjunto de datos de test\ny_pred = pipeline.predict(X_test)\n\n'

##### Scaler- Estratificación
Forzar que las particiones sigan la distribución original de los datos

In [18]:
'''
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
'''

'\nscaler = StandardScaler()\nX_scaled = scaler.fit_transform(X)\n'

####  Cross validation - Validación cruzada
 

#### IMPORTANTE USAR STRATIFIEDKFOLD PARA QUE SE MANTENGA LA DISTRIBUCIÓN. 
PASAMOS EL OBJETO QUE DEVUELVE STRATIFIEDKFOLD COMO PARÁMETRO EN EL MÉTODO QUE HACE LA VALIDACIÓN CRUZADA, BAJO EL NOMBRE cv.

In [19]:
#from sklearn.model_selection import cross_val_score, StratifiedKFold

df = pd.read_csv('datos\datos10.csv')
print(df.info())

# Dividir el conjunto de datos en variables (X) y etiquetas (y)
X = df.drop(columns=['clase_objetivo'])
y = df['clase_objetivo']

#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Dividir en conjuntos de entrenamiento y test


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

  
 ################################################### PIPELINE ################################################### 
# Definir los trnsformers necesarios
numeric_features = ['variable1', 'variable2']
categorical_features = ['variable_categorica']

# Crear el pipeline de preprocesamiento
preprocessor = ColumnTransformer(
    transformers=[ 
        ('num', Pipeline(steps=[
            ('imputer', SimpleImputer(strategy='mean')), 
            ('scaler', StandardScaler()) 
        ]), numeric_features),
        ('cat', Pipeline([
            ('imputer', SimpleImputer(strategy='most_frequent')),
            ('encoder', OneHotEncoder(handle_unknown='ignore'))
        ]), categorical_features)
    ]) 
# Incluir el clasificador en el pipeline
modelo = KNeighborsClassifier(n_neighbors=3)

# Crear el pipeline final
pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', modelo)
])

# Entrenar el modelo en el conjunto de datos de entrenamiento !!!!!!!!!!!!!!!!!! important
pipeline.fit(X_train, y_train)


# Relizar la validación cruzada usando el pipeline sobre el conjunto de entrenamiento
cv_train_scores = cross_val_score(pipeline, X_train, y_train, cv=5, scoring='accuracy')

# Ver resultados
print(f'Cross-Validation Scores: {cv_train_scores}')
print(f'Mean Accuracy: {np.mean(cv_train_scores):.2f}')

# Hacer las predicciones en el conjunto de datos de evaluación
y_pred = pipeline.predict(X_test)

# Evaluar los resultados en el conjunto de datos de evaluación
accuracy_test = accuracy_score(y_test, y_pred)
print("Test Accuracy:", accuracy_test) 

########################## MOSTRAR MATRICES DE CONFUSION PARA CADA FOLD ################################################### 
#from sklearn.model_selection import cross_val_predict

# Realizar la validación cruzada usando cross_val_predict para obtener predicciones en cada iteración
y_train_pred_cv = cross_val_predict(pipeline, X_train, y_train, cv=5) #fijate aqui no usa scoring accuracy precisamente para poder ver la matriz entera luego al crear el objeto

# Calcular y mostrar la matriz de confusión para cada iteración de la validación cruzada
for i in range(5):  # Suponiendo 5-fold cross-validation
    cm = confusion_matrix(y_train, y_train_pred_cv)
    print(f"\nConfusion Matrix - Fold {i + 1}:\n", cm)

# Hacer predicciones en el conjunto de datos de evaluación
y_pred_test = pipeline.predict(X_test)

# Calcular y mostrar la matriz de confusión en el conjunto de prueba
cm_test = confusion_matrix(y_test, y_pred_test)
print("\nConfusion Matrix - Test Set:\n", cm_test)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 4 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   variable1            90 non-null     float64
 1   variable2            88 non-null     float64
 2   variable_categorica  100 non-null    object 
 3   clase_objetivo       100 non-null    object 
dtypes: float64(2), object(2)
memory usage: 3.3+ KB
None
Cross-Validation Scores: [0.375  0.5    0.25   0.5    0.1875]
Mean Accuracy: 0.36
Test Accuracy: 0.35

Confusion Matrix - Fold 1:
 [[19  3  9]
 [16  4  6]
 [ 9  8  6]]

Confusion Matrix - Fold 2:
 [[19  3  9]
 [16  4  6]
 [ 9  8  6]]

Confusion Matrix - Fold 3:
 [[19  3  9]
 [16  4  6]
 [ 9  8  6]]

Confusion Matrix - Fold 4:
 [[19  3  9]
 [16  4  6]
 [ 9  8  6]]

Confusion Matrix - Fold 5:
 [[19  3  9]
 [16  4  6]
 [ 9  8  6]]

Confusion Matrix - Test Set:
 [[1 3 0]
 [2 4 1]
 [4 3 2]]


### ESCOGER LOS MEJORES HIPERPARÁMETROS

Por ejemplo, en el caso de los vecinos más cercanos, ¿para qué valor de 
 funciona mejor? - LO PODEMOS AUTOMATIZAR CON gridsearch

Como los conjuntos de validación durante la validación cruzada se utilizarán para tomar decisiones sobre el modelo, 
de nuevo corremos el riesgo de que exista data leaking.

    PARA EVITAR DATA LEAKING, haremos dos procesos de validación, uno dentro de entrenamiento y otro EXTERNO  
    
            1- en ENTRENAMIENTO aplicamos CROSS VALIDATION
            

            2 - tenemos un conjunto de test a parte 

In [20]:
# Cargar el conjunto de datos
df = pd.read_csv('datos/datos09.csv')
print(df.info())
print(df.describe())
X = df.drop('Clase', axis = 1)
y = df[['Clase']]

# Dividir el conjunto de datos en conjuntos de entrenamiento y test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

#from sklearn.model_selection import GridSearchCV

# Definir un diccionario con hiperparámetros
param_grid = {'n_neighbors': [3, 7, 11]}

# Inicializar el modelo de vecinos más cercanos
modelo = KNeighborsClassifier()

# Crear un objeto de búsqueda
grid_search = GridSearchCV(modelo, param_grid, cv=5, scoring='accuracy')
grid_search

# Realizar la búsqueda sobre el conjunto de entrenamiento
grid_search.fit(X_train, y_train.values.ravel())

# Mirar los resultados obtenidos
grid_search.cv_results_
 

 # Obtener los mejores hiperparámetros y el modelo
best_k = grid_search.best_params_['n_neighbors']
best_model = grid_search.best_estimator_

# Pronosticar sobre el conjunto de datos de test
y_pred = best_model.predict(X_test)

# Calcular la accuracy y la matriz de confusion
accuracy = accuracy_score(y_test, y_pred)    
conf_matrix = confusion_matrix(y_test, y_pred)

# Print the results
print(f'Mejor valor de k: {best_k}')
print(f'Accuracy: {accuracy:.2f}')
print('Matriz de confusión:\n', conf_matrix)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 21 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       1000 non-null   float64
 1   1       1000 non-null   float64
 2   2       1000 non-null   float64
 3   3       1000 non-null   float64
 4   4       1000 non-null   float64
 5   5       1000 non-null   float64
 6   6       1000 non-null   float64
 7   7       1000 non-null   float64
 8   8       1000 non-null   float64
 9   9       1000 non-null   float64
 10  10      1000 non-null   float64
 11  11      1000 non-null   float64
 12  12      1000 non-null   float64
 13  13      1000 non-null   float64
 14  14      1000 non-null   float64
 15  15      1000 non-null   float64
 16  16      1000 non-null   float64
 17  17      1000 non-null   float64
 18  18      1000 non-null   float64
 19  19      1000 non-null   float64
 20  Clase   1000 non-null   int64  
dtypes: float64(20), int64(1)
memory usage:

## Matriz de confusión

In [21]:
#from sklearn.metrics import accuracy_score, confusion_matrix
'''
# To evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)

print(f'Accuracy: {accuracy:.2f}')
print('Matriz de confusión:\n', conf_matrix)
'''

"\n# To evaluate the model\naccuracy = accuracy_score(y_test, y_pred)\nconf_matrix = confusion_matrix(y_test, y_pred)\n\nprint(f'Accuracy: {accuracy:.2f}')\nprint('Matriz de confusión:\n', conf_matrix)\n"